interface JournalEntry {
  id: string;
  title: string;
  content: string;
  category: string;
  date: string;
  user: string;
}
export const sampleJournal: JournalEntry[] = [
  {
    id: "1a",
    title: "Sample Title",
    content: "Sample Content",
    category: "Sample Category",
    date: "2024-07-04",
    user: "23489h23h234rfh",
  },
  {
    id: "1b",
    title: "Sample Title",
    content: "Sample Content",
    category: "Sample Category",
    date: "2024-07-04",
    user: "23489h23h234rfh",
  },
  {
    id: "1c",
    title: "Sample Title",
    content: "Sample Content",
    category: "Sample Category",
    date: "2024-07-04",
    user: "23489h23h234rfh",
  },
  {
    id: "1d",
    title: "Sample Title",
    content: "Sample Content",
    category: "Sample Category",
    date: "2024-07-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2a",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "a2",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2d",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2x",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2j",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2y",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2i",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2o",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2z",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "z2",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "aa",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "x2",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "q2",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2q",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "2w",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
  {
    id: "r2",
    title: "Sample Title Twice",
    content: "Sample Content Twice",
    category: "Sample Category Twice",
    date: "2024-06-04",
    user: "23489h23h234rfh",
  },
];
